export const POKEMON_GET = 'POKEMON_GET';
export const POKEMON_FETCH = 'POKEMON_FETCH';
export const POKEMON_SORT_FETCH = 'POKEMON_SORT_FETCH';
export const POKEMON_FETCH_MORE = 'POKEMON_FETCH_MORE';
export const POKEMON_SORT_BY_LOWEST_NUMBER = 'POKEMON_SORT_BY_LOWEST_NUMBER';
export const POKEMON_SORT_BY_HIGHEST_NUMBER = 'POKEMON_SORT_BY_HIGHEST_NUMBER';
export const POKEMON_SORT_BY_A_Z = 'POKEMON_SORT_BY_A_Z';
export const POKEMON_SORT_BY_Z_A = 'POKEMON_SORT_BY_Z_A';
export const POKEMON_SEARCH = 'POKEMON_SEARCH';

export const TYPES_FETCH = 'TYPES_FETCH';

export const ABILITIES_FETCH = 'ABILITIES_FETCH';
