export const POKEMON_FETCH = 'POKEMON_FETCH';
export const POKEMON_FETCH_MORE = 'POKEMON_FETCH_MORE';
export const POKEMON_SORT_BY_LOWEST_NUMBER = 'POKEMON_SORT_BY_LOWEST_NUMBER';
export const POKEMON_SORT_BY_HIGHEST_NUMBER = 'POKEMON_SORT_BY_HIGHEST_NUMBER';
export const POKEMON_SORT_BY_A_Z = 'POKEMON_SORT_BY_A_Z';
export const POKEMON_SORT_BY_Z_A = 'POKEMON_SORT_BY_Z_A';
export const POKEMON_SEARCH = 'POKEMON_SEARCH';
